
blank_issues_enabled: false
contact_links:
  - name: Yarn v1 documentation
    url:  https://legacy.yarnpkg.com/en/docs
    about: Please visit the documentation for v1.x.x before opening a bug report
